# https://github.com/iggredible/dotfiles/blob/master/.tmux.conf

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

bind -T prefix q display-panes -d 0

bind | split-window -hc "#{pane_current_path}"
bind _ split-window -vc "#{pane_current_path}"

setw -g mode-keys vi
bind-key -T copy-mode-vi 'v'   send -X rectangle-off \; send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X rectangle-on \; send -X begin-selection
bind-key -T copy-mode-vi Escape {
    if-shell -F "#{selection_present}" {
        # true
        send-keys -X clear-selection
    } {
        # false
        send-keys -X cancel
    }
}
bind -T copy-mode-vi y send-keys -X copy-pipe "pbcopy" \; send -X clear-selection
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "pbcopy" \; send -X clear-selection

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Resizing pane
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g mouse on
bind-key m set-option -g mouse \; display-message "Mouse mode: #{?mouse,on,off}"


# tmux messages are displayed for 5 seconds
set -g display-time 5000

set -g default-terminal "xterm-256color"

# yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# synchronize panes
bind-key y set-window-option synchronize-panes
set -g status-right "#{?pane_synchronized, #[bg=red] PANES SYNCED #[default],} %H:%M %d-%b-%y"

